<h1>THINK SPOT TERMS OF USE</h1>
<br />
<p>EFFECTIVE DATE:  FEBRUARY 15, 2010</p>


<p>Welcome to THINK Spot (spot.thinkglobalschool.com).  THINK Spot is operated for Think Global School (“TGS”) students and faculty (“Spot”).  Spot has members-only areas that are governed by these Think Global School Spot Terms of Use (“Spot Terms”).  If you have not been authorized by TGS to become a member of Spot, you are not authorized to use these areas of Spot.</p>  

<p>LOGGING INTO OR USING SPOT WILL BE YOUR REPRESENTATION AND WARRANTY THAT YOU ARE AN AUTHORIZED MEMBER AND YOUR AGREEMENT TO THE SPOT TERMS (INCLUDING ANY AMENDMENT TO THEM), WITHOUT MODIFICATION BY YOU.  If you do not so warrant or agree, do not log-in or use Spot and return to, or cancel with TGS all of your access credentials.  </p>

<p>Each user of Spot (“you”) agrees to the following terms and conditions:</p>

<h2>INCORPORATED TERMS</h2>

<p><strong>Master Terms of Use.</strong>  The Spot Terms include all terms and conditions of the Think Global School Terms of Use (“Master Terms”), which you should review and download or print by visiting http://thinkglobalschool.com/.  The Master Terms, which are incorporated into and made a part of these Spot Terms by this reference,  constitute the bulk of the Spot Terms, and by logging into or using Spot you acknowledge that you have reviewed and agree to the full Master Terms.  These Spot Terms may be amended in the same way as the Master Terms.</p>
<p><strong>THINK Global School Electronic Information Systems, Devices & Social Media Policy.</strong>  The Spot Terms include all terms and conditions of the TGS Electronic Information Systems, Devices & Social Media Policy; that policy is incorporated herein and a copy is available in both the TGS Faculty Handbook and the TGS Student/Parent Handbook, which are available in the members-only areas of Spot. </p>
<p><strong>Definitions.</strong>  Terms used but not defined in the Spot Terms have the definitions set forth in the Master Terms, except that “Site” (as defined in the Master Terms) shall also include the members-only areas of Spot.  </p>

<h2>Supplemental Terms for Spot</h2>

<p>The following terms and conditions apply in addition to the Master Terms.  If there is a conflict between these Spot Terms and the Master Terms, the more specific provision of these Spot Terms will control the conflict.  You ratify your previous agreement to the Master Terms and also agree to these Spot Terms:</p>
<p><strong>Members Only.</strong>   Spot’s members-only areas are for use only by persons who: (a) are enrolled TGS students; (b) are the parent or legal guardian of an enrolled TGS student who has been authorized by TGS to use Spot; (c) are a faculty member or other employee of TGS; or (d) have otherwise been authorized by TGS to use Spot (collectively “Members”).  Not all Members will have the same rights and access; Member rights and access will be determined in the sole discretion of TGS.  You represent and warrant that you are a person described above and that you have received from TGS’s Chief Technology Officer Spot access credentials that you have not shared them with anyone else (and that you did not receive them from anyone other than TGS’s Chief Technology Officer).  You also agree to keep your access credentials confidential and not to allow anyone else to use them.</p>
<p><strong>Spot Purposes; TGS Communications.</strong>   Spot is for daily use by Members to share information with each other in pursuit of TGS’ educational courses and mission, to discuss common concerns (among some or all Members), to let other Members know about recent accomplishments or publications of students or faculty, and otherwise to attempt to deal with the needs of and to support TGS and the TGS community.  TGS will also use Spot to post important information (such as report cards), notices or other information needed by or of interest to Members generally or to particular Members, such as to allow parent-teacher conferences.  You agree to use Spot daily that will allow you to keep abreast of TGS information intended for you.  In extraordinary situations, TGS might send you an email to alert you to postings on Spot, but TGS operations will be based on its assumption that you will check Spot daily. </p>
<h3>Third Party Systems and Services that We Use</h3>
<p>TGS and Spot use and incorporate many Third Party Services, as that term is defined in the TGS Supplemental Policy to the TGS Privacy and Information Security Policy.  These Third Party Services provide many of the services that TGS and Spot use, including e-mail, videos, images, blogging and micro-blogging, and voice over IP (“VOIP”).  Your use of these Third Party Services is governed not only by these Spot Terms, but also by the policies of those Third Party Services.  You agree to review and comply with those policies before using any Third Party Services, as your use may constitute your consent to those policies.  In addition to complying with these Spot Terms you must also comply with terms of Third Party Services which may be unique or different.  For example: </p>

<div class='elgg-output'>
<ul class='elgg-output'>
	<li>TGS or Spot may permit you to use Skype, or another VOIP Third Party Service.  Skype wants us to warn you that you cannot use or rely upon Skype to make emergency calls.  Other VOIP Third Party Services that we use may have similar limitations.</li>
	<li>The licenses that you provide to Third Party Services (including by using those services or uploading, posting, or transferring content to Third Party Services) may be broad in scope, and may limit your rights to such content. </li>
</ul>
</div>

<p><strong>Additional Restrictions.</strong>  In addition to the restrictions set forth in the Master Terms, you agree:</p>
<div class='elgg-output'>
<ul>
	<li>To learn about the different levels of privacy that TGS intends to provide for information and content that you choose to upload or submit on Spot.  You also agree to abide by those levels of privacy, for the information and content that you upload or submit about yourself (e.g., if you want information and content to have limited access, you must select the appropriate privacy setting), as well as for other Members and individuals.  You agree to obtain the consent of any Members or individuals prior to uploading or submitting any information or content about them, or that otherwise identifies them. </li>
	<li>Not to use Spot or any information available from Spot unlawfully or for illegal purposes, in breach of the Spot Terms or the terms of any other contract with TGS or consent that a member provided TGS, in violation of an academic or ethical code of conduct, or to advertise or market to other Members;</li>
	<li>To respect the privacy and personal information of all Members and to honor your obligations under all TGS contracts and policies.  In addition, you agree to treat as confidential information everything on the Members-only areas of Spot that is either marked confidential, that is included in a restricted area, or that a reasonable person ought to know is confidential or otherwise sensitive or protected by concepts of data protection or privacy.  You should assume that all areas of Spot are intended to be Members-only except for areas or materials expressly designated as non-confidential or public;</li>
	<li>You agree not to exceed your authorized access to Spot.  For example, if you are only authorized to use Spot for “X” purpose(s) or to obtain certain documents, you agree not to use it for “Y” purpose(s) or to obtain other documents.</li>
</ul>
</div>

<p><strong>Information from Members Is Not Binding on TGS.</strong> TGS agreements and policies are not subject to or modified by these Spot Terms or information on Spot.  For example, a comment by a TGS employee chatting on Spot does not amend or waive your obligations under contracts or policies with TGS – they remain in full force and effect.  For example, if you “report” something to a TGS employee on Spot, that does not relieve you of any obligation to provide notice under a TGS policy or contract – you must still comply with that obligation.  Also, any opinions, advice, statements, assistance, services, offers, or information expressed or made available by Members on Spot, including employees, do not necessarily reflect those of TGS.  You agree that if you seek a binding amendment to or interpretation of anything, e.g., of a TGS contract or policy, you will contact TGS at “Our Legal Notice Address,” as set forth in the Master Terms, and will not rely on Spot comments which may or may not be accurate or authorized.</p>
<p><strong>Information; Inaccuracies.</strong> TGS reserves the right to remove, add or change any information or document at any time and without notice.  Also, information may be or become outdated or contain typographical errors, inaccuracies, or omissions (collectively, “Inaccuracy”), and TGS reserves the right to correct any Inaccuracy even if an action based upon it has already been taken.  We apologize for any inconvenience this may cause.</p>
<p><strong>Your Indemnity.</strong> You hereby release, hold harmless, and indemnify TGS and its affiliates (and their respective employees, directors and representatives) against any and all claims, actions, proceedings, or suits and all liabilities, damages, settlements, penalties, fines, costs or expenses (including, without limitation, reasonable attorneys' fees and other litigation expenses) incurred by TGS, arising out of or relating to: (a) the violation or breach by you of any term, condition, representation or warranty in the Master Terms, Spot Terms, or applicable Third Party Service policy; (b) your negligence or intentional misconduct; (c) any compromise of confidential information wholly or partly caused by or relating to your actions or inactions; and (d) any unauthorized access to or use: (i) of Spot, or a Third Party Service that TGS or Spot uses, using your access credentials or (ii) of any information that was obtained from Spot, or a Third Party Service that TGS or Spot uses, with use of your access credentials.</p>

<h2>LEGAL NOTICES</h2>
<p><strong>NOTICE:  MONITORING OF SITE USAGE:</strong>   TGS intends the Members-only areas of Spot to be used only by Members and reserves the right to monitor, intercept, retrieve and otherwise use and disclose, all access, use, transmissions and communications.  This includes but is not limited to all uses by employees, parents, students and anyone else.  It also includes (without limitation) monitoring of keystrokes and our use of software to log, analyze and document areas of Spot visited, transmissions to or from Spot and files downloaded, and related information exchanges.  TGS supervisors, law enforcement, and others may receive reports of monitoring information and discipline or legal action may be based upon it, including (without limitation) termination of access, employment or enrollment.  We also reserve the right to disclose monitoring information for other lawful purposes.</p>
